<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="7" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-09T17:03:49 IST" name="Default suite" finished-at="2024-12-09T17:04:12 IST" duration-ms="22905">
    <groups>
    </groups>
    <test started-at="2024-12-09T17:03:49 IST" name="Default test" finished-at="2024-12-09T17:04:12 IST" duration-ms="22905">
      <class name="com.ixfi.testcases.StatusPageTest">
        <test-method is-config="true" signature="loadConfiguration()[pri:0, instance:com.ixfi.testcases.StatusPageTest@53045c6c]" started-at="2024-12-09T17:03:48 IST" name="loadConfiguration" finished-at="2024-12-09T17:03:49 IST" duration-ms="746" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfiguration -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ixfi.testcases.StatusPageTest@53045c6c]" started-at="2024-12-09T17:03:49 IST" name="setup" finished-at="2024-12-09T17:03:57 IST" duration-ms="7584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:com.ixfi.testcases.StatusPageTest@53045c6c]" started-at="2024-12-09T17:03:57 IST" name="setUpTest" finished-at="2024-12-09T17:03:57 IST" duration-ms="46" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="validateTradeInfoSectionTableData_CurrentStateByServices()[pri:0, instance:com.ixfi.testcases.StatusPageTest@53045c6c]" started-at="2024-12-09T17:03:57 IST" name="validateTradeInfoSectionTableData_CurrentStateByServices" finished-at="2024-12-09T17:04:11 IST" duration-ms="14361" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 4 out of bounds for length 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 2
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at com.ixfi.testcases.StatusPageTest.validateTradeInfoSectionTableData_CurrentStateByServices(StatusPageTest.java:252)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTradeInfoSectionTableData_CurrentStateByServices -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ixfi.testcases.StatusPageTest@53045c6c]" started-at="2024-12-09T17:04:11 IST" name="tearDown" finished-at="2024-12-09T17:04:12 IST" duration-ms="879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.ixfi.testcases.StatusPageTest@53045c6c]" started-at="2024-12-09T17:04:12 IST" name="afterSuite" finished-at="2024-12-09T17:04:13 IST" duration-ms="730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.ixfi.testcases.StatusPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
